// Security utilities: bcrypt password hashing, rate limiting, input sanitization, XSS prevention
// PHASE 1 HARDING SÉCURITÉ - Migration SHA256 → bcrypt

import { RateLimiterMemory } from 'rate-limiter-flexible';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';

// ============================================================================
// CONFIGURATION
// ============================================================================

// Bcrypt configuration (production-grade)
const BCRYPT_ROUNDS = 12; // Cost factor: 2^12 = 4096 rounds (recommended 10-12)

// ============================================================================
// RATE LIMITING
// ============================================================================

export const rateLimiters = {
  auth: new RateLimiterMemory({
    points: 5, // 5 attempts
    duration: 900, // 15 minutes
  }),
  api: new RateLimiterMemory({
    points: 100, // 100 requests
    duration: 60, // per minute
  }),
  upload: new RateLimiterMemory({
    points: 10,
    duration: 300, // 5 minutes
  }),
  // New: aggressive rate limiter for sensitive operations
  sensitive: new RateLimiterMemory({
    points: 3,
    duration: 3600, // 1 hour
  }),
};

// ============================================================================
// PASSWORD HASHING (BCRYPT - Production Ready)
// ============================================================================

/**
 * Hash a password using bcrypt (industry standard)
 * - Uses salt automatically generated by bcrypt
 * - Cost factor of 12 (2^12 = 4096 rounds)
 * - Resistant to rainbow tables and brute force
 */
export async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, BCRYPT_ROUNDS);
}

/**
 * Verify a password against a bcrypt hash
 * - Timing-safe comparison (prevents timing attacks)
 * - Works with both bcrypt hashes and legacy SHA256 (migration support)
 */
export async function verifyPassword(password: string, hash: string): Promise<boolean> {
  // Check if it's a legacy SHA64 hash (64 hex chars) or bcrypt hash ($2a$/$2b$ prefix)
  if (hash.startsWith('$2a$') || hash.startsWith('$2b$') || hash.startsWith('$2y$')) {
    // Modern bcrypt hash
    return bcrypt.compare(password, hash);
  } else if (hash.length === 64 && /^[a-f0-9]{64}$/i.test(hash)) {
    // Legacy SHA256 hash - verify and recommend migration
    const legacyHash = crypto.createHash('sha256').update(password + (process.env.PASSWORD_SALT || 'dpata-salt-2024')).digest('hex');
    return legacyHash === hash;
  }
  // Fallback for plain text passwords (should not happen in production)
  return password === hash;
}

/**
 * Migrate a legacy password hash to bcrypt
 * Call this after successful login with legacy hash
 */
export async function migratePasswordHash(password: string): Promise<string> {
  return hashPassword(password);
}

// ============================================================================
// INPUT SANITIZATION (XSS Prevention)
// ============================================================================

/**
 * Sanitize string input to prevent XSS attacks
 * Escapes HTML special characters
 */
export function sanitizeInput(str: string): string {
  if (typeof str !== 'string') return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
    .replace(/\//g, '&#x2F;')
    .trim();
}

/**
 * Sanitize object recursively - all string values are escaped
 */
export function sanitizeObject(obj: Record<string, any>): Record<string, any> {
  const sanitized: Record<string, any> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === 'string') {
      sanitized[key] = sanitizeInput(value);
    } else if (Array.isArray(value)) {
      sanitized[key] = value.map(item => 
        typeof item === 'string' ? sanitizeInput(item) : 
        typeof item === 'object' && item !== null ? sanitizeObject(item) : item
      );
    } else if (typeof value === 'object' && value !== null) {
      sanitized[key] = sanitizeObject(value);
    } else {
      sanitized[key] = value;
    }
  }
  return sanitized;
}

// ============================================================================
// SECURE TOKEN GENERATION
// ============================================================================

/**
 * Generate cryptographically secure random token
 */
export function generateToken(length: number = 32): string {
  return crypto.randomBytes(length).toString('hex');
}

/**
 * Generate CSRF token for form protection
 */
export function generateCSRFToken(): string {
  return generateToken(32);
}

// ============================================================================
// CSRF PROTECTION
// ============================================================================

/**
 * Validate CSRF token with timing-safe comparison
 */
export function validateCSRFToken(token: string, sessionToken: string): boolean {
  if (!token || !sessionToken) return false;
  try {
    return crypto.timingSafeEqual(Buffer.from(token), Buffer.from(sessionToken));
  } catch {
    return false;
  }
}

// ============================================================================
// SECURITY HEADERS HELPERS
// ============================================================================

/**
 * Get security headers for API responses
 */
export function getSecurityHeaders(): Record<string, string> {
  return {
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
  };
}

// ============================================================================
// INPUT VALIDATION HELPERS
// ============================================================================

/**
 * Validate email format
 */
export function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

/**
 * Validate password strength
 * Returns object with isValid and reasons for invalid passwords
 */
export function validatePasswordStrength(password: string): {
  isValid: boolean;
  strength: 'weak' | 'medium' | 'strong';
  errors: string[];
} {
  const errors: string[] = [];
  
  if (password.length < 8) errors.push('Minimum 8 caractères');
  if (password.length > 128) errors.push('Maximum 128 caractères');
  if (!/[A-Z]/.test(password)) errors.push('Une majuscule requise');
  if (!/[a-z]/.test(password)) errors.push('Une minuscule requise');
  if (!/[0-9]/.test(password)) errors.push('Un chiffre requis');
  
  let strength: 'weak' | 'medium' | 'strong' = 'weak';
  if (password.length >= 12 && /[A-Z]/.test(password) && /[a-z]/.test(password) && /[0-9]/.test(password) && /[^A-Za-z0-9]/.test(password)) {
    strength = 'strong';
  } else if (password.length >= 8 && ((/[A-Z]/.test(password) && /[a-z]/.test(password)) || /[0-9]/.test(password))) {
    strength = 'medium';
  }
  
  return {
    isValid: errors.length === 0,
    strength,
    errors,
  };
}

// ============================================================================
// ERROR SANITIZATION (Prevent information leakage)
// ============================================================================

/**
 * Sanitize error message for production - prevent leaking internal details
 */
export function sanitizeError(error: unknown): { error: string; code?: string } {
  if (error instanceof Error) {
    // In production, don't expose internal error details
    if (process.env.NODE_ENV === 'production') {
      console.error('[ERROR]', error.message); // Log internally
      return { error: 'Une erreur est survenue', code: 'INTERNAL_ERROR' };
    }
    // In development, provide more details
    return { error: error.message, code: error.name };
  }
  return { error: 'Une erreur inconnue est survenue' };
}
