// app/api/users/[id]/reset-password/route.ts — P4-C NEW: admin password reset
//
// POST /api/users/[id]/reset-password
//   SUPER_ADMIN only (or FACULTY_ADMIN for users in their faculty)
//   Body (optional): { "newPassword"?: string }
//     - If newPassword is omitted, a random 16-char password is generated.
//     - If provided, must meet strength requirements (min 8 chars, 1 upper, 1 digit).
//
// Behavior:
//   1. Hash the new password with bcrypt (cost 12).
//   2. Update user.passwordHash and user.passwordChangedAt = now().
//   3. Set user.forcedLogoutAt = now() to invalidate the user's existing JWT
//      (forces re-login with the new password).
//   4. Emit audit log entry: action='RESET_PASSWORD', entity='User'.
//   5. Return 200 with { success, newPassword } — newPassword is only
//      returned when it was auto-generated, so the admin can communicate
//      it to the user out-of-band.
//
// Security notes:
//   - The auto-generated password is returned ONLY to the SUPER_ADMIN who
//     initiated the reset. It is NEVER logged or persisted in plaintext.
//   - The user's existing JWT becomes invalid immediately (via forcedLogoutAt).
//   - Self-reset is allowed (admin changing own password) — this is a
//     legitimate use case for forgotten passwords.

import { NextRequest, NextResponse } from 'next/server';
import { loadDB, saveDB, now, audit } from '@/lib/store/db';
import { getCurrentUser } from '@/lib/auth/jwt';
import { hashPassword, getSecurityHeaders, sanitizeError } from '@/lib/security';
import crypto from 'crypto';

export const dynamic = 'force-dynamic';

// Character set for random password generation.
// Excludes ambiguous characters (0/O, 1/l/I) for readability.
const PASSWORD_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
const AUTO_PASSWORD_LENGTH = 16;

/**
 * Generate a cryptographically-secure random password of the given length.
 * Uses crypto.randomBytes for entropy (NOT Math.random).
 */
function generateRandomPassword(length: number = AUTO_PASSWORD_LENGTH): string {
  const bytes = crypto.randomBytes(length);
  const chars: string[] = [];
  for (let i = 0; i < length; i++) {
    chars.push(PASSWORD_ALPHABET[bytes[i] % PASSWORD_ALPHABET.length]);
  }
  const password = chars.join('');
  // Guarantee at least one uppercase, one lowercase, one digit by replacing
  // fixed positions. This avoids the rare case where the random draw misses
  // a required character class.
  return (
    password.slice(0, 6) +
    'A' + // uppercase
    'b' + // lowercase
    '5' + // digit
    password.slice(9)
  ).slice(0, length);
}

/**
 * Validate password strength:
 *   - Minimum 8 characters
 *   - At least 1 uppercase letter
 *   - At least 1 digit
 * Returns { isValid, errors }.
 */
function validatePassword(password: string): { isValid: boolean; errors: string[] } {
  const errors: string[] = [];
  if (password.length < 8) errors.push('Minimum 8 caractères');
  if (!/[A-Z]/.test(password)) errors.push('Une majuscule requise');
  if (!/[0-9]/.test(password)) errors.push('Un chiffre requis');
  return { isValid: errors.length === 0, errors };
}

interface ResetPasswordBody {
  newPassword?: string;
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    // RBAC: SUPER_ADMIN or FACULTY_ADMIN.
    const admin = await getCurrentUser();
    if (!admin) {
      return NextResponse.json(
        { error: 'Non authentifié', code: 'AUTH_REQUIRED' },
        { status: 401, headers: getSecurityHeaders() }
      );
    }
    if (admin.role !== 'SUPER_ADMIN' && admin.role !== 'FACULTY_ADMIN') {
      return NextResponse.json(
        { error: 'Permissions insuffisantes', code: 'FORBIDDEN' },
        { status: 403, headers: getSecurityHeaders() }
      );
    }

    const { id: targetUserId } = await params;
    if (!targetUserId) {
      return NextResponse.json(
        { error: 'ID utilisateur requis', code: 'MISSING_USER_ID' },
        { status: 400, headers: getSecurityHeaders() }
      );
    }

    // Parse body — tolerate empty body.
    let body: ResetPasswordBody = {};
    try {
      const raw = await req.text();
      if (raw && raw.trim().length > 0) {
        body = JSON.parse(raw) as ResetPasswordBody;
      }
    } catch {
      // Malformed JSON — treat as empty body (auto-generate password).
      body = {};
    }

    // Determine the new password: provided or auto-generated.
    const wasAutoGenerated = !body.newPassword;
    const newPassword = body.newPassword || generateRandomPassword(AUTO_PASSWORD_LENGTH);

    // Validate password strength.
    const validation = validatePassword(newPassword);
    if (!validation.isValid) {
      return NextResponse.json(
        {
          error: 'Mot de passe trop faible',
          code: 'WEAK_PASSWORD',
          details: validation.errors,
        },
        { status: 400, headers: getSecurityHeaders() }
      );
    }

    // Extract IP for audit logging.
    const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ||
               req.headers.get('x-real-ip') || undefined;

    const db = await loadDB();
    const targetUser = db.users.find(u => u.id === targetUserId);
    if (!targetUser) {
      return NextResponse.json(
        { error: 'Utilisateur introuvable', code: 'USER_NOT_FOUND' },
        { status: 404, headers: getSecurityHeaders() }
      );
    }

    // FACULTY_ADMIN scope check: can only reset passwords for users in
    // their own faculty.
    if (admin.role === 'FACULTY_ADMIN') {
      if (targetUser.facultyId !== admin.facultyId) {
        return NextResponse.json(
          { error: 'Vous ne pouvez réinitialiser le mot de passe que des utilisateurs de votre faculté', code: 'FACULTY_SCOPE_VIOLATION' },
          { status: 403, headers: getSecurityHeaders() }
        );
      }
      // FACULTY_ADMIN cannot reset a SUPER_ADMIN's password.
      if (targetUser.role === 'SUPER_ADMIN') {
        return NextResponse.json(
          { error: 'Impossible de réinitialiser le mot de passe d\'un super-administrateur', code: 'CANNOT_RESET_SUPER_ADMIN' },
          { status: 403, headers: getSecurityHeaders() }
        );
      }
    }

    // Hash the new password with bcrypt (cost 12).
    const passwordHash = await hashPassword(newPassword);

    const timestamp = now();
    targetUser.passwordHash = passwordHash;
    targetUser.passwordChangedAt = timestamp;
    // Force re-login: invalidate any existing JWT (issued before this timestamp).
    targetUser.forcedLogoutAt = timestamp;
    targetUser.updatedAt = timestamp;

    await saveDB(db);

    // Audit log entry.
    await audit(
      admin.sub,
      `${admin.firstName} ${admin.lastName}`,
      'RESET_PASSWORD',
      'User',
      targetUser.id,
      { targetEmail: targetUser.email, autoGenerated: wasAutoGenerated },
      ip
    );

    // Build response — only return the new password if it was auto-generated.
    const responseBody: Record<string, unknown> = {
      success: true,
      message: 'Mot de passe réinitialisé',
      userId: targetUser.id,
      passwordChangedAt: timestamp,
      forcedReLogin: true,
    };
    if (wasAutoGenerated) {
      responseBody.newPassword = newPassword;
    }

    return NextResponse.json(responseBody, { status: 200, headers: getSecurityHeaders() });
  } catch (e) {
    const error = sanitizeError(e);
    return NextResponse.json(error, { status: 500, headers: getSecurityHeaders() });
  }
}

/**
 * OPTIONS /api/users/[id]/reset-password — CORS preflight.
 */
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      Allow: 'POST, OPTIONS',
      'Cache-Control': 'no-store',
    },
  });
}
