// memoire_ch2.js - Chapitre 2 : État de l'art du plagiat académique
const { Paragraph, PageBreak } = require("docx");

function buildChapter2(h) {
  const { H1, H2, H3, P_body, P_quote, P_bullet, P_caption, P_centered, P_empty, threeLineTable } = h;
  return [
    H1("CHAPITRE II — ÉTAT DE L'ART DU PLAGIAT ACADÉMIQUE ET ANALYSE DES BESOINS"),

    H2("II.1. Introduction"),
    P_body("Le plagiat dans le contexte académique est devenu, depuis une trentaine d'années, une préoccupation majeure pour une proportion grandissante d'établissements d'enseignement supérieur à travers le monde. D'abord largement sous-estimé, le phénomène a vu son importance et l'étude de ses tenants et aboutissants connaître un gain d'intérêt constant, sous l'effet conjugué de la massification de l'enseignement supérieur, de la numérisation des sources documentaires et, plus récemment, de l'apparition des intelligences artificielles génératives. L'avènement des technologies de l'information et de la communication, Internet en tête, suscite encore aujourd'hui un vif débat sur les opportunités qu'elles offrent en matière de recherche, mais aussi en termes de pratiques frauduleuses."),
    P_body("De façon récurrente depuis l'intégration d'Internet dans les institutions académiques, des recherches diffusent en effet l'idée que les possibilités de manipulation de l'information offertes par cette technologie favorisent l'émergence de comportements plagiaires parmi les étudiants. De l'aveu de ceux-ci, ces facilités représentent des causes de plagiat modérément à très pertinentes. Il est donc légitime de s'interroger sur les mécanismes de cette relation et sur les implications d'une augmentation du phénomène, ainsi que sur les réponses techniques et institutionnelles à y apporter."),
    P_body("Le présent chapitre propose un état de l'art du plagiat académique, en mobilisant la littérature scientifique existante et en l'enrichissant pour prendre en compte les nouvelles formes de plagiat apparues avec l'IA générative. Il aborde successivement les définitions du plagiat, ses domaines d'application, ses différents types, les méthodes de détection automatique, les causes et les conséquences du phénomène, ainsi que les mesures de lutte existantes. Il se conclut par une analyse comparative des principaux logiciels anti-plagiat disponibles et par une identification des besoins spécifiques du cadre pilote."),

    H2("II.2. Définition du plagiat"),
    P_body("Le plagiat est une faute d'ordre moral, civil ou commercial, qui peut être sanctionnée au pénal. Il consiste à copier un auteur ou à accaparer l'œuvre d'un créateur dans le domaine des arts sans le citer ou le dire, ainsi qu'à s'inspirer fortement d'un modèle que l'on omet, délibérément ou par négligence, de désigner. Il est souvent assimilé à un vol immatériel, dans la mesure où l'on s'approprie le fruit du travail intellectuel d'autrui pour le présenter comme sien. Le plagiaire est celui qui s'approprie frauduleusement tout ou partie d'une œuvre littéraire, technique, artistique ou scientifique."),
    P_body("Dans le contexte académique, le plagiat recouvre plus largement toute pratique par laquelle un étudiant ou un chercheur présente comme personnel un travail, une idée, une formulation ou un résultat qui provient en réalité d'une source extérieure non citée. Cette définition englobe non seulement la reproduction littérale non référencée, mais aussi la paraphrase non attribuée, la traduction non sourcée, la réutilisation de données sans crédit, l'auto-plagiat (réutilisation de ses propres travaux sans le mentionner) et, depuis peu, l'utilisation non déclarée de contenus produits par des intelligences artificielles génératives."),
    P_body("La frontière entre le plagiat et les pratiques légitimes n'est pas toujours évidente à tracer. Citer un auteur sans reprendre exactement ses mots, sans indiquer la source exacte ou en modifiant légèrement la formulation peut constituer un plagiat selon les standards académiques, même si l'intention de tromper n'est pas présente. C'est cette porosité de la notion qui rend nécessaire l'existence d'outils techniques d'aide à la détection, complémentaires du jugement humain de l'enseignant ou du jury."),

    H2("II.3. Quelques domaines du plagiat"),
    P_body("Le plagiat n'est pas l'apanage du monde académique. Il se rencontre dans de nombreux domaines de l'activité humaine, avec des spécificités propres à chacun."),
    H3("II.3.1. Dans les sciences"),
    P_body("Le plagiat scientifique touche les articles de recherche, les communications, les thèses et les rapports techniques. Il peut prendre la forme de la reproduction de résultats expérimentaux, de l'appropriation d'idées ou de méthodologies, ou de la copie de passages entiers d'articles antérieurs. Les conséquences sont particulièrement lourdes dans ce domaine, car elles affectent la crédibilité de la recherche et peuvent conduire à des rétractations d'articles, à des sanctions professionnelles et à la mise en cause de la validité de travaux ultérieurs qui s'appuient sur les résultats plagiés."),
    H3("II.3.2. Dans le journalisme"),
    P_body("Le plagiat journalistique consiste à reprendre, sans citation, des informations, des enquêtes ou des récits produits par d'autres médias ou d'autres journalistes. Plusieurs affaires médiatiques retentissantes, dans la presse écrite comme à la télévision, ont mis en lumière l'ampleur du phénomène et conduit à des licenciements, des procès et à la perte de crédibilité des organes de presse concernés. La pression de l'immédiateté, la concurrence entre titres et la facilité de l'accès aux sources en ligne constituent des facteurs aggravants."),
    H3("II.3.3. Dans la littérature et les arts"),
    P_body("Le plagiat littéraire et artistique concerne l'appropriation d'œuvres de fiction, de scénarios, de partitions musicales, d'œuvres graphiques ou plastiques. Plusieurs procès célèbres ont opposé des écrivains, des réalisateurs ou des musiciens autour d'accusations de plagiat. La distinction entre influence légitime, hommage et plagiat délibéré y est souvent délicate à établir, et relève autant du droit d'auteur que de la déontologie artistique."),
    H3("II.3.4. Dans le monde académique"),
    P_body("Le plagiat académique, qui constitue le cœur du présent mémoire, concerne les travaux produits dans le cadre d'un cursus d'enseignement : devoirs, dissertations, exposés, travaux de fin de cycle, mémoires, thèses. Il est probablement la forme la plus répandue de plagiat, en raison du nombre d'étudiants concernés, de la pression scolaire et de l'accessibilité des sources. Il affecte l'ensemble des disciplines, des sciences humaines aux sciences dures, et tous les niveaux d'étude, du premier cycle au doctorat."),

    H2("II.4. Types de plagiat"),
    P_body("La littérature scientifique identifie plusieurs types de plagiat, qui diffèrent par leur degré de gravité, leur mode opératoire et leur facilité de détection. Une typologie rigoureuse est importante pour concevoir des outils de détection adaptés et pour évaluer la gravité des cas identifiés."),
    ...threeLineTable(
      ["Type de plagiat", "Description", "Détection"],
      [
        ["Copier-coller strict", "Reproduction littérale sans citation", "Facile (méthodes lexicales)"],
        ["Copier-coller avec références", "Reproduction littérale avec citation, mais sans guillemets", "Moyenne"],
        ["Paraphrase non référencée", "Reformulation d'un passage sans en citer la source", "Difficile (sémantique)"],
        ["Paraphrase patchwork", "Assemblage de paraphrases issues de plusieurs sources", "Difficile"],
        ["Traduction non sourcée", "Traduction d'un texte étranger sans en citer la source", "Très difficile"],
        ["Auto-plagiat", "Réutilisation de ses propres travaux antérieurs sans le mentionner", "Possible par recoupement"],
        ["Plagiat par IA générative", "Production d'un texte par un LLM présenté comme œuvre personnelle", "Très difficile (émergent)"],
        ["Plagiat d'idées", "Appropriation d'une idée, d'un concept ou d'une méthodologie", "Impossible par automate"],
      ],
      "Tableau II.1 — Typologie des principaux types de plagiat académique"
    ),
    P_body("Cette typologie met en évidence l'insuffisance des approches purement lexicales, qui ne détectent efficacement que les deux premiers types. Les approches sémantiques fondées sur les embeddings permettent d'élargir la détection aux paraphrases et aux patchworks, ainsi qu'aux traductions lorsque le modèle d'embeddings est multilingue. Le plagiat par IA générative et le plagiat d'idées restent en revanche des défis partiellement ouverts, qui nécessitent des approches complémentaires."),

    H2("II.5. Détection automatique du plagiat"),
    P_body("La détection automatique du plagiat peut être classée en trois catégories principales, selon l'approche technique retenue."),
    P_body("La première catégorie tente de détecter le style d'écriture et d'identifier les changements incompatibles avec ce style. Elle s'appuie sur des analyses stylométriques (longueur des phrases, richesse du vocabulaire, fréquence de certains mots-outils) et suppose que le plagiat introduit des ruptures stylistiques détectables. Cette approche est intéressante mais peu fiable en pratique, notamment pour les travaux étudiants dont le style n'est pas encore stabilisé."),
    P_body("La deuxième catégorie est la plus utilisée. Elle se base sur la comparaison entre plusieurs documents et l'identification des chevauchements de parties entre ces documents. Plusieurs techniques sont mobilisées : le fingerprinting, qui représente chaque document comme un ensemble d'empreintes de sous-chaînes (n-grammes) et compare ces empreintes ; le string matching, qui compare les documents mot par mot en utilisant des algorithmes comme Brute Force ou Rabin-Karp ; l'analyse des citations, qui examine les séquences de références bibliographiques partagées entre documents. Ces techniques sont efficaces pour la détection du copier-coller strict, mais aveugles aux reformulations."),
    P_body("La troisième catégorie reçoit un document en entrée et recherche les motifs de plagiat dans le Web, de manière manuelle ou automatisée. Elle est utilisée par des services commerciaux comme Turnitin ou Compilatio, qui disposent d'index massifs de pages web et de travaux antérieurs. Cette approche nécessite une connexion Internet, un abonnement souvent coûteux, et soulève des questions de confidentialité lorsqu'on confie à un tiers les travaux des étudiants."),
    P_body("Les approches modernes, fondées sur l'IA et les embeddings vectoriels, complètent ces catégories traditionnelles. Elles ne se limitent pas à la comparaison lexicale, mais mesurent la similarité sémantique entre les passages des documents. Cette approche, retenue dans le présent mémoire, permet de détecter les paraphrases et les reformulations qui échappent aux outils classiques. Elle peut être combinée avec les approches traditionnelles pour maximiser la couverture des différents types de plagiat."),

    H2("II.6. Causes et facteurs du plagiat académique"),
    P_body("Plusieurs études convergent pour identifier un ensemble de facteurs qui favorisent le plagiat en milieu académique. Ces facteurs sont à la fois individuels, institutionnels et technologiques, et leur combinaison explique l'ampleur et la persistance du phénomène."),
    H3("II.6.1. Facteurs individuels"),
    P_body("Au niveau individuel, plusieurs motivations sont fréquemment citées : la pression de la performance scolaire, la peur de l'échec, le manque de temps lié à la conciliation des études avec une activité professionnelle, la difficulté du sujet, le manque de confiance en ses capacités de rédaction, et parfois simplement l'opportunité perçue. Les étudiants les plus en difficulté sont souvent les plus tentés par le plagiat, mais le phénomène touche également des étudiants brillants, en quête d'optimisation de leur temps ou de leur note."),
    H3("II.6.2. Facteurs institutionnels"),
    P_body("Au niveau institutionnel, plusieurs éléments favorisent le plagiat : l'absence de formation méthodologique à la citation et à la rédaction scientifique, l'insuffisance des sanctions en cas de plagiat avéré, l'absence d'outils techniques de détection, le caractère impersonnel des cours en amphithéâtre qui facilite l'anonymat des étudiants, et parfois l'inadéquation entre les exigences académiques et les moyens accordés aux étudiants pour y répondre. La culture institutionnelle, notamment la tolérance plus ou moins grande vis-à-vis du copier-coller, joue également un rôle déterminant."),
    H3("II.6.3. Facteurs technologiques"),
    P_body("Au niveau technologique, l'accessibilité des sources numériques (articles en ligne, encyclopédies collaboratives, blogs, dépôts de mémoires accessibles), la facilité du copier-coller, l'existence d'outils de paraphrase automatique, et désormais la disponibilité gratuite des grands modèles de langage conversationnels, constituent autant de facilités technologiques. Les enquêtes menées auprès des étudiants estiment que quatre étudiants sur cinq ont déjà eu recours au copier-coller, et que la proportion a significativement augmenté depuis la diffusion massive de ChatGPT fin 2022."),

    H2("II.7. Approches économiques et sociologiques du plagiat"),
    P_body("Au-delà des facteurs individuels et technologiques, le plagiat académique peut être analysé à travers le prisme des sciences économiques et sociales. Plusieurs cadres théoriques éclairent ce phénomène sous un angle complémentaire, en mettant en lumière les mécanismes rationnels et sociaux qui sous-tendent les comportements plagiaires."),
    H3("II.7.1. Approche économique : le choix rationnel"),
    P_body("Dans une approche économique néoclassique (Becker, 1968), le plagiat peut être considéré comme un crime d'individus en quête d'une maximisation de l'utilité de cette activité. Dans ce cadre, le passage à l'acte dépend de l'espérance pour le décideur d'obtenir une satisfaction en fonction des ressources et du temps dont il dispose, mais aussi de la probabilité de sanction. L'activité criminelle est supposée varier en raison inverse de la répression : l'intensité du délit diminue au fur et à mesure que le risque et la gravité des sanctions augmentent."),
    P_body("La décision de plagier ou non résulte ainsi d'un choix rationnel des étudiants selon une estimation de type coût-avantage. Les plagiaires doivent arbitrer entre les avantages du plagiat (meilleure note, validation de tout ou partie du diplôme) et le risque afférent (un zéro, invalidation du diplôme ou de l'année d'étude, passage devant une commission disciplinaire). La minimisation du risque nécessite l'emploi de formes de plagiat difficilement détectables mais coûteuses, telles que l'emploi d'un tiers pour réaliser le travail. Les théories de la dissuasion (Paternoster, 1987) considèrent que les sanctions devraient s'accentuer avec la diffusion des pratiques délictueuses : dès lors que l'accès aux travaux universitaires est plus aisi, notamment par l'intermédiaire d'Internet, les institutions devraient renforcer leurs moyens de détection."),
    P_body("Cependant, les résultats empiriques montrent que la théorie du choix rationnel est peu efficiente pour expliquer le plagiat étudiant. Si les plagiaires minimisent le temps consacré aux études, ils maîtrisent mal les avantages à tirer du plagiat et méconnaissent le risque de sanctions : environ 81% des étudiants n'ont jamais lu de compte rendu de conseil de discipline et seuls 16% d'entre eux connaissent la sanction encourue. Ce sont davantage les formes de socialisation antérieures, le rapport aux études et l'incompréhension des règles universitaires qui expliquent ce phénomène."),
    H3("II.7.2. Approche sociologique : la déviance"),
    P_body("L'approche sociologique du plagiat se situe principalement dans le champ de la déviance. La sociologie nord-américaine fournit les principales références théoriques. La déviance est construite sur des normes sociales et juridiques dont les sociologues ont montré qu'elles sont fluctuantes. Pour les interactionnistes (Lemert, Becker, Goffman), la déviance est un processus construit par des réactions sociales qui transforment un agissement en infraction. Pour Becker (1963), le déviant est un acteur qui progressivement et de manière rationnelle fait carrière : il développe des compétences et les fait valoir comme dans toute activité sociale."),
    P_body("L'apprentissage pratique des techniques de la tricherie et celui de la rationalisation des attitudes favorables à la déviance (Sutherland & Cressey, 1966) se font avant l'entrée à l'université. D'autres explications accordent plus d'importance à l'incompréhension des attentes universitaires (Coulon, 1987) : le plagiat résulterait alors d'un malentendu entre les attentes de l'institution pas toujours explicites et celles d'étudiants qui considèrent la charge de travail trop pesante. Ce malentendu peut conduire certains à tricher sans avoir le sentiment de le faire."),

    H2("II.8. Conceptions du plagiat chez les étudiants"),
    P_body("L'efficacité toute relative des solutions mises en place par les institutions a motivé certains chercheurs à adopter une autre perspective dans la recherche sur le plagiat. Ashworth et al. (2003) dénoncent les réponses du monde académique face au phénomène plagiaire, en ce qu'elles présupposent chez les étudiants la présence d'un ensemble de conceptions uniforme relatif au processus de création du savoir. En recueillant les conceptions des étudiants par le biais d'entretiens phénoménologiques, ils assurent que les réponses ne sont pas influencées par les cadres éthiques déjà en vigueur."),
    P_body("Il ressort de ces travaux que les conceptions du plagiat chez les étudiants interrogés varient considérablement. Tout d'abord, les conceptions ne sont jamais alignées avec les valeurs académiques « officielles ». Les étudiants ne les perçoivent pas comme universelles, mais plutôt propres à certaines facultés ou certains établissements. La façon de les décrire dénote un manque de familiarité avec les contextes et principes qui rendent pertinente la définition de ces valeurs. Enfin, les étudiants sont sensibles à la dimension sociale de leur travail : proposer à un collègue dans le besoin de plagier son propre travail apparaît comme acceptable, tandis que la crainte d'être publiquement exposé suite à un acte plagiaire constitue une des barrières principales à ce comportement."),
    P_body("Gullifer et Tyson (2010), dans une recherche par focus groupes, ont également montré que les conceptions des étudiants à propos du plagiat restent vagues, indépendamment de leur âge, niveau d'étude ou champ disciplinaire. Un consensus important émerge toutefois à propos de l'existence du plagiat inconscient (ou involontaire) : celui-ci est jugé comme étant courant chez les étudiants, en raison d'un manque de connaissances-clefs sur le cadre académique et de compétences pour pouvoir s'y adapter. Une partie de la responsabilité est ici renvoyée au corps institutionnel, rappelant l'importance de la mise en place de chartes éthiques claires et accessibles (Park, 2003)."),
    P_body("Sutton et al. (2014) ont développé un questionnaire destiné à déterminer quels types d'actes les étudiants regroupent sous le label du plagiat, et quels degrés de gravité leur sont attribués. Des résultats de l'étude, administrée auprès d'environ 2500 étudiants, se dégagent trois facteurs principaux : les comportements dits « malhonnêtes » (vol du travail d'autrui, achat d'un travail en ligne), jugés comme les plus graves ; le travail en groupe non officiel, considéré comme la catégorie la moins sévère ; et le référencement insuffisant, d'une sévérité intermédiaire. Le manque de consensus sur le concept de plagiat entre étudiants et corps enseignant constitue un problème critique que les institutions doivent adresser pour construire une politique efficace de promotion de l'intégrité académique."),

    H2("II.9. Conséquences du plagiat"),
    P_body("Les conséquences du plagiat académique sont multiples et concernent à la fois l'étudiant, l'institution et la société dans son ensemble."),
    P_body("Pour l'étudiant, le plagiat, lorsqu'il est détecté, expose à des sanctions pouvant aller de l'annulation de l'épreuve à l'exclusion définitive de l'établissement. Au-delà des sanctions formelles, le plagiat non détecté conduit à une dégradation des apprentissages : en contournant l'effort de production personnelle, l'étudiant se prive de l'acquisition de compétences essentielles (recherche, analyse, synthèse, rédaction, esprit critique). À terme, des diplômes obtenus partiellement par plagiat peuvent conduire à des incompétences professionnelles aux conséquences graves, notamment dans les métiers à responsabilité."),
    P_body("Pour l'institution, le plagiat non maîtrisé entraîne une dévalorisation des diplômes délivrés et une perte de crédibilité scientifique. Les employeurs et les institutions partenaires, en constatant l'incapacité des diplômés à produire un travail original, peuvent perdre confiance dans la valeur des certifications. Les universités engagées dans des partenariats internationaux ou dans des démarches d'accréditation sont particulièrement vulnérables sur ce point, l'intégrité académique étant un critère central d'évaluation."),
    P_body("Pour la société, le plagiat académique contribue à une dégradation générale de la confiance dans les productions intellectuelles et scientifiques. Lorsque les travaux de recherche, les rapports techniques ou les publications contiennent des éléments plagiés, la validité des connaissances produites est compromise. Dans les domaines sensibles (santé, ingénierie, droit), les conséquences peuvent être directes et parfois dramatiques. La lutte contre le plagiat s'inscrit donc dans une politique plus large de préservation de l'intégrité intellectuelle."),

    H2("II.10. Mesures de lutte contre le plagiat"),
    P_body("La lutte contre le plagiat académique mobilise plusieurs leviers complémentaires, qui doivent être articulés pour une efficacité maximale. Aucune mesure isolée n'est suffisante : c'est la combinaison d'actions pédagogiques, institutionnelles et techniques qui produit des résultats durables."),
    H3("II.10.1. Mesures pédagogiques"),
    P_body("Sur le plan pédagogique, plusieurs actions sont recommandées : la formation des étudiants aux règles de la citation et de la rédaction scientifique dès le début du cursus, l'intégration de modules sur l'intégrité académique dans les enseignements transversaux, l'accompagnement personnalisé des étudiants en difficulté par des séances de méthodologie, et la conception de sujets de travaux qui réduisent les opportunités de plagiat (sujets originaux, contextualisés, exigeant une réflexion personnelle). Les formations méthodologiques menées seules, sans contrôle effectif, ne font que faiblement baisser le recours au copier-coller : elles doivent donc être combinées à des dispositifs de détection."),
    H3("II.10.2. Mesures institutionnelles"),
    P_body("Sur le plan institutionnel, il convient de mettre en place une politique d'intégrité académique explicite, formalisée dans un règlement intérieur et portée par les autorités de l'établissement. Cette politique doit définir clairement ce qui constitue une faute, les sanctions applicables, la procédure de traitement des cas avérés, et les droits de la défense. Un engagement signé par chaque étudiant en début d'année, attestant de la compréhension des règles d'intégrité, peut constituer un dispositif complémentaire utile. La transparence des sanctions (sans nécessairement nommer les contrevenants) participe à la prévention."),
    H3("II.10.3. Mesures techniques"),
    P_body("Sur le plan technique, le déploiement d'outils de détection automatique du plagiat constitue un complément indispensable. Ces outils permettent d'une part de dissuader les pratiques plagiaires (effet préventif lié à la connaissance de l'existence du contrôle), d'autre part d'identifier les cas effectifs pour traitement pédagogique ou sanctionnaire. Plusieurs solutions commerciales existent (Turnitin, Compilatio, Urkund), mais leur coût, leur dépendance à des bases de données externes et les questions de confidentialité posées par l'envoi des travaux étudiants à des serveurs étrangers limitent leur adoption dans le contexte africain. Le développement d'une solution locale, comme celle proposée dans ce mémoire, répond à ces enjeux."),

    H2("II.11. Plagiat assisté par IA générative"),
    P_body("Depuis la mise à disposition publique des grands modèles de langage conversationnels à partir de fin 2022, une nouvelle forme de plagiat est apparue dans le monde académique : le plagiat assisté par IA générative. Cette forme de plagiat consiste pour l'étudiant à faire produire tout ou partie de son travail par un modèle d'IA tel que ChatGPT, Claude, Gemini ou un outil similaire, puis à le présenter comme œuvre personnelle."),
    P_body("Cette pratique pose des défis inédits aux dispositifs de détection. Contrairement au plagiat classique, le texte produit par l'IA n'existe dans aucune source antérieure identifiable : il est généré à la demande, en fonction d'une consigne. Les outils de comparaison de documents, même les plus avancés, sont donc impuissants à le détecter par leur mécanisme habituel. Plusieurs approches émergent pour tenter d'identifier ces productions : analyse de la perplexité du texte (un texte généré par IA présente une perplexité moyenne plus faible, car les LLM produisent statistiquement les tokens les plus probables), analyse stylométrique (certains motifs lexicaux et syntaxiques sont caractéristiques des LLM), utilisation de classificateurs supervisés entraînés sur des corpus de textes humains et de textes IA. Aucune de ces approches n'est à ce jour pleinement satisfaisante, avec des taux de faux positifs et de faux négatifs significatifs, et des risques d'accusation injustifiée d'étudiants ayant produit un travail authentique."),
    P_body("L'évolution rapide des LLM (GPT-3.5, GPT-4, GPT-4o, Claude 3, Gemini 1.5 Pro, etc.) rend la détection particulièrement difficile : chaque génération de modèles produit des textes de plus en plus proches des productions humaines, et les classificateurs entraînés sur les générations antérieures deviennent rapidement obsolètes. Plusieurs universités ont d'ailleurs renoncé à utiliser des détecteurs de texte IA, estimant que leur fiabilité était insuffisante et que leur usage pouvait conduire à des accusations infondées. La détection du plagiat par IA générative constitue ainsi l'un des fronts de recherche les plus actifs du domaine, et fait l'objet d'une attention particulière dans les perspectives de ce mémoire."),

    H2("II.12. Techniques modernes de paraphrase automatique"),
    P_body("La paraphrase automatique désigne l'ensemble des techniques permettant de transformer un texte source en un texte cible sémantiquement équivalent mais formellement différent. Ces techniques, longtemps rudimentaires (substitution de synonymes, restructuration syntaxique simple), ont été considérablement améliorées par les modèles de langage récents. Un LLM comme GPT-4 est aujourd'hui capable de produire en quelques secondes une paraphrase fluide et grammaticalement correcte d'un paragraphe donné, modifiant le vocabulaire, la structure des phrases et l'ordre des idées tout en préservant le sens."),
    P_body("Cette capacité de paraphrase automatique constitue un défi direct pour les outils de détection du plagiat fondés sur la comparaison lexicale. Un étudiant peut, à partir d'un texte source non cité, produire une version paraphrasée qui passera inaperçue aux outils classiques, tout en étant sémantiquement équivalente à l'original. Les approches sémantiques basées sur les embeddings, comme celle proposée dans ce mémoire, sont mieux armées pour identifier ce type de plagiat, dans la mesure où elles comparent le sens des passages plutôt que leur forme. Toutefois, les paraphrases très sophistiquées produites par les LLM récents peuvent même tromper les modèles d'embeddings, ce qui souligne la nécessité de combiner plusieurs approches."),
    P_body("Les techniques de paraphrase automatique peuvent également être utilisées de manière positive, comme outil pédagogique pour aider les étudiants à améliorer leur rédaction ou à comprendre les mécanismes de la reformulation. Cette double nature (outil de fraude potentielle et outil d'apprentissage) illustre la complexité du paysage académique contemporain, où les mêmes technologies peuvent être mises au service de l'intégrité ou de la tricherie."),

    H2("II.13. Limites des logiciels classiques"),
    P_body("Les logiciels classiques de détection du plagiat, bien qu'utiles, présentent plusieurs limites bien documentées. La première limite est leur incapacité à détecter les paraphrases et les reformulations syntaxiques : en comparant des chaînes de mots, ils ne voient pas les passages dont le sens est identique mais la formulation différente. La deuxième limite est leur insensibilité aux traductions : un passage traduit d'une langue étrangère sans citation de la source originale échappera à toute détection, à moins que l'outil ne dispose d'un mécanisme de comparaison multilingue."),
    P_body("La troisième limite est l'incapacité à détecter le plagiat par IA générative, dans la mesure où le texte produit n'existe dans aucune source antérieure. Les logiciels classiques ne voient rien, puisqu'ils ne trouvent aucune correspondance dans leur base. Cette limite est devenue critique depuis 2022 et rend nécessaires les évolutions vers des approches complémentaires."),
    P_body("La quatrième limite concerne les questions de confidentialité et de souveraineté des données. Les principaux logiciels commerciaux (Turnitin, Compilatio) fonctionnent en envoyant le document à vérifier sur des serveurs externes, généralement situés à l'étranger. Cette pratique pose problème dans plusieurs contextes : confidentialité des travaux étudiants, propriété intellectuelle des institutions, conformité avec les réglementations locales sur la protection des données. Dans le contexte africain, s'ajoutent la dépendance technologique, le coût des licences en devises fortes, et l'absence de prise en compte des spécificités linguistiques et disciplinaires locales."),
    P_body("Enfin, les logiciels classiques ne distinguent pas les signes diacritiques comme les guillemets, les chevrons, l'italique ou le gras. Ils ne peuvent détecter l'emprunt d'idées, ni juger du sens d'une rédaction. Les paraphrases et autres bricolages syntaxiques échappent à la majorité d'entre eux, tout comme les traductions effectuées à l'aide de logiciels. C'est cette accumulation de limites qui justifie le développement d'approches nouvelles, fondées sur l'IA et la similarité sémantique."),

    H2("II.14. Comparaison avec les plateformes modernes"),
    P_body("Plusieurs plateformes modernes ont fait évoluer leurs approches pour intégrer les techniques d'IA. Le tableau suivant synthétise une comparaison entre solutions commerciales existantes et l'approche proposée dans ce mémoire."),
    ...threeLineTable(
      ["Plateforme", "Approche", "Multilingue", "Confidentialité", "Coût", "Adaptation locale"],
      [
        ["Turnitin", "Lexicale + web", "Limitée", "Données envoyées à l'étranger", "Élevé (devise forte)", "Faible"],
        ["Compilatio", "Lexicale + IA", "Français/anglais", "Données envoyées à l'étranger", "Élevé", "Moyenne"],
        ["Urkund", "Lexicale + web", "Plusieurs langues", "Données envoyées à l'étranger", "Élevé", "Faible"],
        ["Plateforme proposée", "Sémantique (embeddings)", "Multilingue (SBERT)", "Données hébergées localement", "Maîtrisé", "Forte (corpus local)"],
      ],
      "Tableau II.2 — Comparaison entre plateformes anti-plagiat existantes et solution proposée"
    ),
    P_body("Cette comparaison met en évidence les avantages différenciants de la solution proposée : adaptation au contexte linguistique et disciplinaire local, hébergement des données sur l'infrastructure nationale, maîtrise du coût, et capacité à évoluer vers une détection interuniversitaire grâce à son architecture modulaire. La plateforme ne prétend pas concurrencer les solutions commerciales sur la taille de leur index web, mais offre une alternative pertinente pour le contexte universitaire congolais et africain, en s'appuyant sur un corpus local de travaux académiques et sur les techniques modernes de similarité sémantique."),

    H2("II.15. Conclusion"),
    P_body("Ce chapitre a présenté un état de l'art du plagiat académique, en intégrant les évolutions récentes liées à l'IA générative. Le plagiat, dans ses formes classiques (copier-coller, paraphrase, traduction, auto-plagiat) comme dans ses formes émergentes (production par LLM), constitue un défi majeur pour l'intégrité académique. Les outils classiques de détection, fondés sur la comparaison lexicale, présentent des limites qui rendent nécessaires les approches sémantiques modernes. La plateforme proposée dans ce mémoire s'inscrit dans cette dynamique, en combinant embeddings vectoriels, similarité cosinus et architecture modulaire, tout en répondant aux spécificités du contexte local."),
    P_body("Le chapitre suivant sera consacré à la conception de la plateforme : architecture générale, modularité, pipeline IA, modélisation des données et interface fonctionnelle. Il fera le lien entre les fondements théoriques posés dans le chapitre I, l'état de l'art dressé dans le présent chapitre, et l'implémentation qui fera l'objet du chapitre IV."),
    new Paragraph({ children: [new PageBreak()] }),
  ];
}

module.exports = { buildChapter2 };
