// memoire_ch1.js - Chapitre 1 : Fondements de l'IA appliquée à la détection du plagiat
const { Paragraph, PageBreak } = require("docx");

function buildChapter1(h) {
  const { H1, H2, H3, P_body, P_quote, P_bullet, P_caption, P_centered, P_empty, threeLineTable } = h;
  return [
    H1("CHAPITRE I — FONDEMENTS DE L'INTELLIGENCE ARTIFICIELLE APPLIQUÉE À LA DÉTECTION AUTOMATIQUE DU PLAGIAT"),

    H2("I.1. Introduction"),
    P_body("Ce chapitre pose les fondements théoriques et techniques nécessaires à la compréhension du présent mémoire. Il replace d'abord l'Intelligence Artificielle dans son contexte historique et conceptuel, avant d'introduire les principaux paradigmes qui sous-tendent les systèmes modernes de traitement automatique du langage : le machine learning, le deep learning, et plus spécifiquement les modèles fondés sur l'architecture Transformer. Il présente ensuite les notions d'embeddings vectoriels, de similarité cosinus, de recherche vectorielle et d'IA générative, qui constituent le socle technique de la plateforme proposée. Le chapitre se conclut par un état de l'art synthétique des approches modernes de détection automatique du plagiat fondées sur l'IA."),
    P_body("L'objectif n'est pas de produire un traité exhaustif d'Intelligence Artificielle, mais de fournir au lecteur les repères indispensables pour comprendre les choix techniques opérés dans les chapitres suivants. Les notions introduites ici seront mobilisées à la fois dans la conception de la plateforme (chapitre III) et dans son implémentation (chapitre IV)."),

    H2("I.2. Intelligence Artificielle : définition et évolution"),
    P_body("L'Intelligence Artificielle (IA) peut être définie comme l'ensemble des techniques visant à doter des systèmes informatiques de capacés cognitives habituellement considérées comme propres à l'intelligence humaine : perception, raisonnement, apprentissage, compréhension du langage, prise de décision. Le terme est introduit formellement en 1956 lors de la conférence de Dartmouth, à l'initiative de John McCarthy, Marvin Minsky, Nathaniel Rochester et Claude Shannon. Depuis lors, le domaine a connu plusieurs cycles d'expansion et de repli, marqués par des hivers successifs suivis de renaissances spectaculaires."),
    P_body("On distingue traditionnellement l'IA faible, qui conçoit des systèmes capables d'accomplir une tâche précise (jouer aux échecs, reconnaître une image, traduire un texte), de l'IA forte, qui viserait à doter une machine d'une compréhension générale et d'une conscience comparable à celle de l'homme. La quasi-totalité des systèmes opérationnels à ce jour relèvent de l'IA faible, y compris les grands modèles de langage les plus performants. La plateforme proposée dans ce mémoire s'inscrit dans ce cadre : il s'agit d'une IA spécialisée dans la détection de similarités textuelles, et non d'un système doté d'une compréhension générale du monde académique."),
    P_body("L'évolution de l'IA peut être schématiquement divisée en trois grandes vagues. La première vague, des années 1950 aux années 1980, est dominée par les approches symboliques et les systèmes experts, fondés sur la représentation explicite de connaissances sous forme de règles logiques. La deuxième vague, à partir des années 1990, est celle de l'apprentissage statistique, où les systèmes apprennent des régularités à partir de grandes quantités de données. La troisième vague, à partir des années 2010, est celle du deep learning, qui exploite des réseaux de neurones profonds pour apprendre des représentations hiérarchiques complexes. Le présent mémoire s'inscrit explicitement dans cette troisième vague."),
    P_body("Plus récemment, l'année 2022 a marqué un tournant avec l'apparition des grands modèles de langage conversationnels accessibles au grand public, tels que ChatGPT. Ces modèles, fondés sur l'architecture Transformer et entraînés sur des corpus textuels massifs, sont capables de produire des textes cohérents sur des sujets très variés. Leur diffusion pose un défi inédit à l'intégrité académique, car ils rendent possible la génération quasi instantanée de travaux universitaires complets, ce qui impose en retour l'évolution des dispositifs de détection du plagiat."),

    H2("I.3. Machine Learning"),
    P_body("Le Machine Learning, ou apprentissage automatique, est la branche de l'Intelligence Artificielle qui concerne la conception de systèmes capables d'apprendre à partir de données, sans être explicitement programmés pour chaque cas traité. Tom Mitchell propose une définition formelle souvent citée : « un programme informatique apprend d'une expérience E, vis-à-vis d'une tâche T et d'une mesure de performance P, si sa performance sur T, mesurée par P, s'améliore avec l'expérience E ». Cette définition met l'accent sur l'amélioration graduelle des performances par l'exposition aux données, par opposition à la programmation par règles."),
    P_body("On distingue traditionnellement trois grands paradigmes d'apprentissage. L'apprentissage supervisé consiste à entraîner un modèle à partir d'un ensemble de données étiquetées, où chaque exemple est associé à la sortie attendue. L'apprentissage non supervisé, à l'inverse, travaille sur des données non étiquetées et cherche à en découvrir la structure intrinsèque, par exemple en regroupant les exemples similaires. L'apprentissage par renforcement, enfin, conçoit des agents qui apprennent par essais et erreurs, en recevant des récompenses ou des pénalités pour leurs actions. La détection de plagiat telle qu'abordée dans ce mémoire relève principalement de l'apprentissage non supervisé, les embeddings vectoriels étant calculés sans étiquetage manuel des cas de plagiat."),
    P_body("Dans le contexte de la détection automatique du plagiat, le machine learning intervient à plusieurs niveaux. Il permet tout d'abord de produire des représentations vectorielles des phrases et des paragraphes, qui capturent le sens du texte au-delà de sa forme superficielle. Il permet ensuite de calculer des scores de similarité entre ces représentations, d'identifier les passages potentiellement plagiés et de les classer par ordre de pertinence. Enfin, il autorise l'apprentissage de seuils optimaux de décision, à partir d'un corpus étiqueté de cas avérés de plagiat, afin de minimiser les faux positifs et les faux négatifs."),

    H2("I.4. Deep Learning"),
    P_body("Le Deep Learning, ou apprentissage profond, est une sous-discipline du machine learning qui repose sur l'utilisation de réseaux de neurones artificiels comportant un grand nombre de couches. L'adjectif « profond » fait référence à la profondeur du réseau, c'est-à-dire au nombre de couches de traitement successives entre l'entrée et la sortie. Cette profondeur permet au modèle d'apprendre des représentations hiérarchiques des données, chaque couche transformant la représentation de la couche précédente pour en extraire des informations de plus en plus abstraites."),
    P_body("Un neurone artificiel, ou unité, calcule une combinaison linéaire de ses entrées, à laquelle il applique une fonction d'activation non linéaire (sigmoïde, ReLU, tanh, etc.). L'assemblage de plusieurs neurones en couches successives constitue un réseau de neurones. L'apprentissage consiste à ajuster les poids des connexions entre neurones afin de minimiser une fonction de coût, mesurant l'écart entre les prédictions du modèle et les sorties attendues. Cette optimisation est généralement réalisée par la méthode de rétropropagation du gradient (backpropagation), combinée à un algorithme d'optimisation tel que la descente de gradient stochastique."),
    P_body("Plusieurs architectures de deep learning ont marqué le domaine du traitement automatique du langage naturel. Les réseaux de neurones récurrents (RNN) et leur variante LSTM (Long Short-Term Memory) ont longtemps dominé le traitement des séquences textuelles, en raison de leur capacité à prendre en compte la dépendance entre les mots successifs. Les réseaux convolutifs (CNN), initialement développés pour la vision par ordinateur, ont également été adaptés au texte. Mais c'est l'architecture Transformer, introduite par Vaswani et al. en 2017, qui a constitué la véritable rupture, en remplaçant la récurrence par un mécanisme d'attention permettant de modéliser directement les relations entre tous les mots d'une séquence, indépendamment de leur position."),

    H2("I.5. Traitement Automatique du Langage Naturel (NLP)"),
    P_body("Le Traitement Automatique du Langage Naturel (TALN), ou Natural Language Processing (NLP) en anglais, est la branche de l'Intelligence Artificielle qui s'intéresse à la compréhension, à l'analyse et à la génération du langage humain par des systèmes informatiques. Le NLP se situe à l'intersection de l'informatique, de la linguistique et de l'apprentissage automatique. Il couvre un large éventail de tâches : traduction automatique, analyse de sentiment, résumé automatique, reconnaissance d'entités nommées, question-réponse, classification de texte, et bien sûr détection de similarité textuelle."),
    P_body("Le traitement d'un texte par un système NLP passe généralement par plusieurs étapes préliminaires. La tokenisation consiste à découper le texte en unités discrètes (tokens), qui peuvent être des mots, des sous-mots ou des caractères selon l'approche retenue. La normalisation regroupe les opérations de mise en minuscules, de suppression de la ponctuation, de suppression des accents ou de traitement des abréviations. La lemmatisation ramène chaque mot à sa forme canonique (le lemme), tandis que la racinisation (stemming) se contente d'en extraire une racine approximative. L'étiquetage morphosyntaxique (POS tagging) associe à chaque token sa catégorie grammaticale. Enfin, la reconnaissance d'entités nommées identifie les personnes, lieux, organisations, dates et autres entités mentionnées dans le texte."),
    P_body("Ces étapes préalables, longtemps considérées comme indispensables, tendent à être intégrées dans les modèles modernes fondés sur l'architecture Transformer. Les modèles comme BERT (Bidirectional Encoder Representations from Transformers), introduit par Devlin et al. en 2018, apprennent des représentations contextuelles des mots, c'est-à-dire que la représentation d'un mot dépend de l'ensemble du contexte dans lequel il apparaît. Cette contextualisation constitue un progrès majeur par rapport aux embeddings statiques comme Word2Vec ou GloVe, où chaque mot avait une représentation unique quelle que soit la phrase dans laquelle il apparaissait."),
    P_body("Dans le contexte de la détection automatique du plagiat, le NLP intervient à plusieurs étapes du pipeline proposé. Il assure le prétraitement des documents (nettoyage, segmentation, normalisation), la production des embeddings vectoriels des phrases et paragraphes, et l'analyse fine des similarités détectées (par exemple pour distinguer une citation correctement référencée d'un plagiat caractérisé)."),

    H2("I.6. Embeddings vectoriels"),
    P_body("Les embeddings vectoriels constituent la pierre angulaire des approches modernes de similarité textuelle. Un embedding est une représentation vectorielle d'une unité linguistique (mot, phrase, paragraphe, document) dans un espace vectoriel de dimension réduite, généralement comprise entre 100 et 1500 dimensions. Cette représentation est apprise de manière à ce que des unités sémantiquement proches correspondent à des vecteurs proches dans l'espace, au sens d'une métrique de distance telle que la distance euclidienne ou la similarité cosinus."),
    P_body("Historiquement, les premiers travaux sur les embeddings ont porté sur la représentation des mots. Le modèle Word2Vec, proposé par Mikolov et al. en 2013, repose sur l'idée que la représentation d'un mot peut être apprise en prédisant les mots qui apparaissent dans son voisinage. GloVe (Global Vectors), proposé par Pennington et al. en 2014, s'appuie sur la matrice de co-occurrence des mots. Ces modèles produisent des embeddings statiques, c'est-à-dire qu'un mot donné est toujours représenté par le même vecteur, quelle que soit la phrase dans laquelle il apparaît. Cette limite est levée par BERT, qui produit des embeddings contextuels."),
    P_body("Pour représenter des unités plus longues que le mot (phrase, paragraphe, document), plusieurs stratégies sont possibles. La plus simple consiste à calculer la moyenne des embeddings des mots qui composent l'unité. Cette approche, rapide, souffre toutefois de limites sémantiques : elle ignore l'ordre des mots et perd une partie de l'information contextuelle. Le modèle Sentence-BERT, introduit par Reimers et Gurevych en 2019, propose une approche plus sophistiquée : il fine-tune BERT spécifiquement pour produire des embeddings de phrases sémantiquement pertinents, en utilisant un mécanisme de pooling sur les représentations de tokens."),
    P_body("Le choix du modèle d'embeddings dépend de plusieurs facteurs : la langue des documents à analyser, la disponibilité de modèles pré-entraînés, les ressources de calcul disponibles, et le compromis entre précision et vitesse. Pour le présent mémoire, le modèle distiluse-base-multilingual-cased-v1, version multilingue de Sentence-BERT, a été retenue en raison de sa capacité à traiter le français et l'anglais, de sa taille réduite (adaptée à un déploiement sur des serveurs aux ressources limitées) et de ses performances documentées sur les tâches de similarité sémantique."),

    ...threeLineTable(
      ["Modèle", "Année", "Type", "Dimension", "Caractéristique principale"],
      [
        ["Word2Vec", "2013", "Statique", "300", "Prédiction de contexte"],
        ["GloVe", "2014", "Statique", "100-300", "Matrice de co-occurrence"],
        ["BERT", "2018", "Contextuel", "768-1024", "Encodeur bidirectionnel"],
        ["Sentence-BERT", "2019", "Phrases", "384-768", "Pooling sémantique"],
        ["multilingual SBERT", "2019+", "Multilingue", "512", "Cross-lingual"],
      ],
      "Tableau I.1 — Principaux modèles d'embeddings vectoriels utilisables pour la détection de plagiat"
    ),

    H2("I.7. Similarité cosinus et métriques de distance"),
    P_body("Une fois les embeddings vectoriels produits, il faut être en mesure de comparer les vecteurs entre eux pour identifier les similarités. Plusieurs métriques de distance ou de similarité peuvent être utilisées. La plus courante dans le contexte du traitement automatique du langage est la similarité cosinus, qui mesure le cosinus de l'angle entre deux vecteurs dans l'espace vectoriel."),
    P_body("Mathématiquement, la similarité cosinus entre deux vecteurs A et B est définie comme le rapport entre leur produit scalaire et le produit de leurs normes euclidiennes. Elle prend ses valeurs entre -1 (vecteurs opposés) et 1 (vecteurs colinéaires), la valeur 0 correspondant à des vecteurs orthogonaux. Dans le contexte des embeddings de texte, où les vecteurs sont généralement positifs, les valeurs sont comprises entre 0 et 1, une valeur proche de 1 indiquant une forte similarité sémantique."),
    P_body("D'autres métriques peuvent être envisagées : la distance euclidienne, qui mesure la distance géométrique entre deux vecteurs ; la distance de Manhattan, qui somme les différences absolues sur chaque dimension ; la distance de Jaccard, adaptée à la comparaison d'ensembles. Pour les embeddings denses produits par les modèles modernes, la similarité cosinus est généralement privilégiée car elle est invariante par mise à l'échelle, ce qui correspond à l'intuition que deux phrases exprimant la même idée avec des longueurs différentes doivent être considérées comme similaires."),
    P_body("Dans la plateforme proposée, un seuil de similarité est défini pour décider si deux passages doivent être considérés comme potentiellement plagiés. Le choix de ce seuil est un compromis entre précision (éviter les faux positifs) et rappel (ne pas manquer de vrais cas de plagiat). Une valeur typiquement utilisée avec Sentence-BERT est de l'ordre de 0,75 à 0,85, mais ce seuil doit être calibré expérimentalement sur le corpus cible."),

    H2("I.8. Recherche vectorielle"),
    P_body("Lorsque le corpus documentaire à comparer devient important, le calcul exhaustif de la similarité entre un document requête et tous les documents de la base devient prohibitif. La recherche vectorielle, ou recherche approximative des plus proches voisins (Approximate Nearest Neighbors ou ANN), adresse ce problème en organisant les vecteurs dans des structures de données permettant une recherche rapide, au prix d'une légère perte de précision."),
    P_body("Plusieurs bibliothèques implémentent ces techniques. FAISS (Facebook AI Similarity Search), développée par Meta, est l'une des plus utilisées en recherche. Elle propose plusieurs index optimisés (IndexFlatL2, IVF, HNSW, PQ) selon le compromis recherché entre vitesse, mémoire et précision. Milvus est une base de données vectorielle distribuée conçue pour la production. Pinecone et Weaviate sont des services managés. Pour les déploiements plus simples, l'extension pgvector de PostgreSQL permet de stocker et de rechercher des vecteurs directement dans une base relationnelle, sans recourir à un système externe."),
    P_body("Dans le contexte de ce mémoire, l'extension pgvector a été retenue pour plusieurs raisons. D'abord, elle s'intègre nativement à PostgreSQL, qui est déjà utilisé pour les données relationnelles de la plateforme (utilisateurs, travaux, analyses), ce qui évite l'introduction d'un système supplémentaire. Ensuite, elle supporte les index HNSW (Hierarchical Navigable Small World) qui offrent d'excellentes performances de recherche. Enfin, elle permet d'utiliser le langage SQL pour exprimer des requêtes combinant critères relationnels et similarité vectorielle, ce qui simplifie l'implémentation."),

    H2("I.9. IA générative et grands modèles de langage"),
    P_body("L'IA générative désigne la branche de l'Intelligence Artificielle qui vise à produire du contenu nouveau (texte, image, audio, vidéo) à partir de modèles appris sur de grandes quantités de données. Dans le domaine textuel, cette IA générative s'appuie sur les grands modèles de langage (Large Language Models ou LLM), dont les plus connus sont la famille GPT (Generative Pre-trained Transformer) d'OpenAI, Claude d'Anthropic, Gemini de Google, et les modèles ouverts comme Llama (Meta), Mistral ou DeepSeek."),
    P_body("Un grand modèle de langage est un modèle neuronal de type Transformer, entraîné sur un corpus textuel massif (plusieurs milliards voire trillions de tokens) à prédire le token suivant dans une séquence. Cette tâche apparemment simple, lorsqu'elle est réalisée à l'échelle, conduit le modèle à internaliser une représentation riche de la syntaxe, de la sémantique et même d'une partie des connaissances factuelles présentes dans les données d'entraînement. Le modèle peut ensuite être spécialisé pour diverses tâches par affinage (fine-tuning) ou par adaptation en contexte (in-context learning)."),
    P_body("L'irruption de l'IA générative dans le champ académique pose un défi inédit à la détection du plagiat. Contrairement au plagiat classique, qui consiste à recopier un texte existant, le plagiat par IA générative produit un texte nouveau, qui n'existe dans aucune source antérieure identifiable. Les outils classiques de détection de similarité sont donc impuissants. Plusieurs approches émergent pour tenter de détecter ce type de plagiat : analyse statistique de la perplexité du texte (un texte généré par IA tend à avoir une perplexité plus faible qu'un texte humain), analyse stylométrique (les LLM ont des tics d'écriture reconnaissables), ou utilisation de classificateurs entraînés à distinguer texte humain et texte généré. Aucune de ces approches n'est à ce jour pleinement satisfaisante, et la détection du plagiat par IA générative constitue un champ de recherche actif, abordé dans ce mémoire comme perspective."),
    P_body("Il convient également de noter que l'IA générative peut être utilisée comme outil de paraphrase automatique, transformant un texte source en un texte différent mais sémantiquement équivalent. Cette utilisation rend plus difficile la détection par les approches lexicales, mais reste partiellement identifiable par les approches sémantiques basées sur les embeddings, qui capturent le sens plutôt que la forme. C'est l'un des arguments en faveur de l'approche retenue dans ce mémoire."),

    H2("I.10. État de l'art de la détection automatique du plagiat par IA"),
    P_body("La détection automatique du plagiat a connu plusieurs générations d'approches. La première génération, dominée par les méthodes de string matching et de fingerprinting, repose sur la comparaison lexicale des documents. L'algorithme de Rabin-Karp, les n-grammes de caractères ou de mots, et les empreintes de Winnowing en sont des exemples caractéristiques. Ces approches sont rapides et efficaces pour la détection des copier-coller stricts, mais incapables d'identifier les paraphrases et les reformulations."),
    P_body("La deuxième génération, à partir des années 2010, introduit des méthodes d'apprentissage statistique. Les modèles de topic modeling (LDA), les embeddings de mots (Word2Vec, GloVe) et les modèles de langue (BERT) commencent à être utilisés pour calculer des similarités sémantiques entre documents. Plusieurs travaux académiques (Potthast et al., Stein et al.) proposent des évaluations systématiques de ces approches, notamment dans le cadre des campagnes PAN (Plagiarism Detection, Author Identification, and Sexual Predator Identification)."),
    P_body("La troisième génération, émergente, s'appuie sur les embeddings de phrases et les modèles Transformer. Sentence-BERT, SimCSE, et plus récemment les embeddings produits par les LLM (text-embedding-ada-002 d'OpenAI, Cohere Embed, etc.) permettent de calculer des similarités sémantiques fines, même entre des phrases reformulées. Ces approches sont aujourd'hui l'état de l'art pour la détection de similarité intra-corpus, mais leur application à grande échelle reste coûteuse en ressources de calcul et en stockage vectoriel."),
    P_body("La quatrième génération, encore balbutiante, tente de détecter le plagiat par IA générative. Les approches combinent classificateurs supervisés, métriques de perplexité, analyse stylométrique et détection de motifs syntaxiques récurrents. Aucune solution mature n'est à ce jour disponible, et ce défi est explicitement identifié comme l'une des perspectives de recherche du présent mémoire."),

    ...threeLineTable(
      ["Génération", "Approche dominante", "Capacités", "Limites"],
      [
        ["1re (années 1990+)", "String matching, fingerprinting", "Copier-coller strict", "Aveugle aux paraphrases"],
        ["2e (années 2010+)", "ML statistique, Word2Vec", "Similarité lexicale étendue", "Pas de contexte"],
        ["3e (années 2019+)", "Sentence-BERT, Transformers", "Similarité sémantique", "Coût de calcul"],
        ["4e (émergente)", "LLM, classificateurs IA", "Détection de texte IA", "Fiabilité partielle"],
      ],
      "Tableau I.2 — Évolution des approches de détection automatique du plagiat"
    ),

    H2("I.11. Conclusion"),
    P_body("Ce chapitre a posé les fondements conceptuels et techniques du mémoire. L'Intelligence Artificielle, de ses origines symboliques aux architectures Transformer contemporaines, fournit aujourd'hui des outils puissants pour le traitement automatique du langage naturel. Les embeddings vectoriels, et en particulier les embeddings de phrases produits par des modèles comme Sentence-BERT, permettent de capturer le sens des textes au-delà de leur forme superficielle. La similarité cosinus, combinée à des techniques de recherche vectorielle approchée, offre une solution efficace pour identifier les similitudes sémantiques entre travaux académiques, à une échelle compatible avec un déploiement opérationnel."),
    P_body("L'émergence récente de l'IA générative et des grands modèles de langage bouleverse en outre le paysage du plagiat académique, en rendant possible la génération automatique de textes difficiles à détecter par les outils classiques. Cette évolution impose le recours aux approches sémantiques modernes et ouvre de nouvelles perspectives de recherche pour identifier les productions automatisées. Le chapitre suivant examinera en détail l'état de l'art du plagiat académique, ses formes, ses causes et ses conséquences, ainsi que les limites des solutions actuellement disponibles sur le marché."),
    new Paragraph({ children: [new PageBreak()] }),
  ];
}

module.exports = { buildChapter1 };
