// memoire_content.js - Module exportant les fonctions de construction des chapitres
const { Paragraph, PageBreak, TextRun, AlignmentType } = require("docx");

// =========================================================================
// INTRODUCTION GÉNÉRALE
// =========================================================================
function buildIntroduction(h) {
  const { H1, H2, H3, P_body, P_quote, P_bullet, P_caption, P_centered, P_empty, threeLineTable } = h;
  return [
    H1("INTRODUCTION GÉNÉRALE"),

    H2("I.1. Préambule"),
    P_body("Longtemps considéré comme tabou dans les milieux académiques, le plagiat est aujourd'hui une préoccupation majeure pour la plupart des établissements d'enseignement supérieur à travers le monde. Les universités, jadis réticentes à aborder publiquement la question par crainte de porter atteinte à leur réputation et à la valeur des diplômes qu'elles délivrent, reconnaissent désormais l'ampleur du phénomène et la nécessité d'y apporter une réponse structurée. Cette prise de conscience s'explique par l'évolution des pratiques étudiantes, l'accessibilité croissante des sources numériques et, plus récemment, l'émergence des outils d'intelligence artificielle générative qui bouleversent les modalités traditionnelles de production de texte."),
    P_body("L'avènement d'Internet a amplifié le phénomène plagiaire en offrant aux étudiants un accès quasi illimité à une masse considérable de documents académiques, d'articles scientifiques, d'encyclopédies collaboratives et de travaux antérieurs. Les enquêtes menées dans plusieurs universités africaines et européennes convergent vers un constat identique : près de quatre étudiants sur cinq reconnaissent avoir eu recours au « copier-coller » au moins une fois au cours de leur parcours universitaire. Cette proportion a encore augmenté depuis 2022 avec la diffusion massive des grands modèles de langage tels que ChatGPT, Claude ou Gemini, capables de produire en quelques secondes des textes cohérents, structurés et difficilement détectables par les logiciels anti-plagiat classiques."),
    P_body("Face à cette évolution, les dispositifs institutionnels de lutte contre le plagiat, lorsqu'ils existent, reposent encore largement sur des comparaisons lexicales mot à mot, sur des empreintes numériques (fingerprinting) ou sur des bases de données fermées. Ces approches, bien qu'utiles, montrent leurs limites face aux reformulations, aux paraphrases automatiques et à la traduction multilingue. La détection du plagiat doit donc évoluer pour intégrer les techniques modernes de l'Intelligence Artificielle, notamment le traitement automatique du langage naturel, les embeddings vectoriels et la similarité sémantique."),
    P_quote("« Le développement d'une plateforme web basée sur l'Intelligence Artificielle pour la détection automatique du plagiat dans les travaux académiques » constitue le thème du présent mémoire. Il s'inscrit dans une dynamique de modernisation des dispositifs d'évaluation de l'originalité des travaux scientifiques produits au sein de l'Université de Kinshasa."),
    P_body("La Faculté des Sciences de l'Université de Kinshasa servira de cadre pilote pour la conception et l'expérimentation de la plateforme. Elle constituera un terrain d'expérimentation permettant de valider la solution avant son extension progressive aux autres facultés et, à terme, à d'autres établissements universitaires nationaux. Le présent travail ne se limite donc pas à la réalisation d'un simple logiciel de comparaison de documents : il propose une plateforme universitaire intelligente, modulaire et évolutive, intégrant un moteur IA de détection automatique du plagiat comme l'un de ses services. La plateforme assure également la gestion des étudiants, des enseignants, des départements, des facultés, le dépôt et l'archivage des travaux académiques, ainsi que la production de rapports automatiques destinés aux enseignants et aux jurys d'évaluation."),

    H2("I.2. Problématique"),
    P_body("La problématique du plagiat académique ne se résume plus, aujourd'hui, à la simple reproduction non déclarée d'un passage d'un ouvrage ou d'un article. Elle s'est considérablement complexifiée avec l'apparition des technologies numériques, l'accessibilité des bases de données scientifiques en ligne, l'usage massif des moteurs de recherche et, depuis 2022, la prolifération des intelligences artificielles génératives capables de produire du contenu textuel à la demande. Les enseignants et les jurys d'évaluation se trouvent ainsi confrontés à des formes de plagiat de plus en plus sophistiquées, difficiles à identifier par une simple lecture ou par des outils de comparaison superficiels."),
    P_body("À la Faculté des Sciences de l'Université de Kinshasa, le constat est sans appel. L'institution ne dispose d'aucun système informatique dédié à la gestion et au contrôle des travaux de fin de cycle (TFC) et des travaux de fin d'études (TFE). Les travaux sont actuellement déposés sous format papier ou électronique, archivés de manière dispersée, sans indexation systématique et sans mécanisme automatique de comparaison entre les productions étudiantes. Cette situation laisse un large champ libre aux pratiques plagiaires, qu'il s'agisse de la reproduction d'un travail antérieur d'un autre étudiant, du copier-coller massif depuis des sources en ligne, ou désormais, de la génération de contenu par des intelligences artificielles conversationnelles."),
    P_body("Plusieurs questions fondamentales découlent de ce constat. Comment détecter efficacement les similitudes entre un travail soumis et l'ensemble des travaux antérieurs déposés au sein de la faculté ? Comment identifier les paraphrases et les reformulations qui échappent aux comparaisons lexicales classiques ? Comment prendre en compte la dimension multilingue des sources exploitées par les étudiants, qui consultent aussi bien des documents en français qu'en anglais ? Comment produire un rapport exploitable par l'enseignant, indiquant non seulement un pourcentage global de similarité, mais aussi les passages précis concernés et les sources correspondantes ? Comment, enfin, concevoir une plateforme suffisamment modulaire pour être étendue à d'autres facultés et à d'autres universités ?"),
    P_body("Les approches classiques de détection du plagiat, fondées sur la comparaison mot à mot, l'analyse des n-grammes, l'empreinte numérique (fingerprinting) ou la recherche de chaînes de caractères (string matching), présentent des limites bien documentées. Elles ne détectent pas les paraphrases, restent aveugles aux reformulations syntaxiques, ignorent les traductions et ne savent pas reconnaître le contenu produit par les grands modèles de langage. Ces limites rendent nécessaire le recours à des techniques modernes d'Intelligence Artificielle, capables d'analyser non plus seulement la forme des textes, mais également leur sens."),
    P_body("La question centrale qui guide ce travail peut être formulée ainsi : dans quelle mesure le développement d'une plateforme web basée sur les techniques modernes d'Intelligence Artificielle, notamment les embeddings vectoriels et la similarité sémantique, permettrait-il d'améliorer significativement la détection automatique du plagiat dans les travaux académiques à la Faculté des Sciences de l'Université de Kinshasa, tout en posant les bases d'une solution extensible à l'ensemble du système universitaire national ?"),

    H2("I.3. Hypothèse du travail"),
    P_body("L'hypothèse principale du présent mémoire est que la conception et le déploiement d'une plateforme universitaire intelligente, fondée sur les techniques modernes d'Intelligence Artificielle et plus particulièrement sur les embeddings vectoriels produits par des modèles de type Sentence-BERT associés à une base de données vectorielle, permettrait de détecter de manière significativement plus efficace les cas de plagiat dans les travaux académiques, par rapport aux approches classiques de comparaison lexicale. Le moteur IA de détection du plagiat, intégré comme un service parmi d'autres au sein d'une plateforme plus large de gestion des travaux académiques, bénéficierait de la centralisation des données étudiantes et documentaires pour produire des analyses pertinentes et exploitables."),
    P_body("Plus précisément, une telle plateforme serait capable d'identifier non seulement les reproductions strictes (copier-coller), mais aussi les paraphrases, les reformulations syntaxiques et potentiellement les traductions, en s'appuyant sur une représentation vectorielle du sens des phrases plutôt que sur la seule comparaison des chaînes de caractères. L'architecture modulaire de la plateforme, organisée en modules par faculté et par département, permettrait son extension progressive à d'autres facultés et universités, sans refonte majeure du système. L'intégration de l'OCR (reconnaissance optique de caractères) garantirait la prise en charge des travaux soumis sous format PDF ou image, et la centralisation de la gestion des utilisateurs, des promotions et des travaux apporterait une valeur ajoutée dépassant largement la seule détection du plagiat."),
    P_body("Cette hypothèse sera validée à travers l'expérimentation de la plateforme sur un corpus pilote de travaux académiques de la Faculté des Sciences, en comparant les performances de l'approche sémantique à celles d'une approche lexicale classique, sur la base de métriques d'évaluation standard de l'apprentissage automatique (précision, rappel, F1-score, courbe ROC)."),

    H2("I.4. Choix et intérêt du sujet"),
    P_body("Le choix du sujet répond à plusieurs motivations complémentaires. Sur le plan scientifique, il s'agit de contribuer à l'application des techniques modernes d'Intelligence Artificielle, et en particulier du traitement automatique du langage naturel, à un problème concret du monde académique africain. La plupart des recherches publiées dans le domaine de la détection automatique du plagiat portent sur des corpus anglophones et utilisent des modèles entraînés principalement sur des textes en anglais. Le présent travail propose d'évaluer la pertinence de ces approches dans un contexte francophone et africain, où les ressources linguistiques sont plus limitées et où les pratiques académiques présentent des spécificités propres."),
    P_body("Sur le plan pédagogique, la plateforme vise à encourager les étudiants à développer un esprit de créativité, d'innovation et d'originalité dans la production de leurs travaux scientifiques. En disposant d'un outil capable de détecter les similitudes avec les travaux antérieurs, l'étudiant est incité à produire un contenu authentique et à citer correctement ses sources. La plateforme constitue ainsi un dispositif à la fois préventif et curatif : préventif parce qu'elle dissuade les pratiques plagiaires, curatif parce qu'elle les identifie lorsqu'elles se produisent."),
    P_body("Sur le plan institutionnel, l'intérêt est de doter la Faculté des Sciences, puis progressivement l'ensemble de l'Université de Kinshasa, d'un outil numérique moderne de gestion et de contrôle des travaux académiques. Cet outil contribue à la valorisation des diplômes délivrés, à la crédibilité scientifique de l'institution et à la conformité aux standards internationaux en matière d'intégrité académique. La valeur d'un diplôme dépend en grande partie de la confiance accordée à l'originalité des travaux qui ont conduit à sa délivrance."),
    P_body("Sur le plan socio-économique enfin, le projet s'inscrit dans une dynamique de renforcement des capacités numériques locales. Le développement de la plateforme mobilise des compétences en programmation, en apprentissage automatique, en conception de bases de données et en déploiement d'applications web. Il participe à la formation d'une nouvelle génération d'informaticiens congolais capables de concevoir, réaliser et maintenir des systèmes d'information complexes, en réduisant la dépendance technologique extérieure."),

    H2("I.5. Délimitation du sujet"),
    P_body("Pour répondre aux normes scientifiques et assurer la faisabilité du travail dans les délais impartis, le présent mémoire est délimité dans le temps, dans l'espace et dans son contenu."),
    H3("I.5.1. Délimitation dans le temps"),
    P_body("L'étude s'étend sur la période correspondant à l'année académique en cours, durant laquelle ont été conduites les activités de revue de la littérature, d'analyse des besoins, de conception, d'implémentation et d'expérimentation de la plateforme. Le corpus pilote de travaux académiques utilisé pour l'évaluation se compose de mémoires et de TFC effectivement déposés à la Faculté des Sciences au cours des cinq dernières années académiques, afin de disposer d'un volume suffisant pour évaluer les performances du système dans des conditions réelles."),
    H3("I.5.2. Délimitation dans l'espace"),
    P_body("Sur le plan spatial, le travail prend la Faculté des Sciences de l'Université de Kinshasa comme cadre pilote d'expérimentation. Ce choix se justifie par la proximité institutionnelle, l'accessibilité du terrain et la disponibilité d'un corpus documentaire suffisant. Toutefois, il convient d'insister sur le fait que la Faculté des Sciences ne constitue pas l'objet du mémoire : elle en est uniquement le terrain d'expérimentation. La plateforme est conçue dès l'origine comme une solution générique, applicable à l'ensemble des facultés de l'Université de Kinshasa et extensible à d'autres établissements d'enseignement supérieur nationaux. L'architecture modulaire retenue met en œuvre une vision hiérarchique claire : chaque faculté devient un module de la plateforme, chaque département un sous-module, chaque promotion un sous-ensemble du département. Cette structuration autorise une extension progressive sans refonte du cœur technique du système, et ouvre la voie à un déploiement à l'échelle nationale."),
    H3("I.5.3. Délimitation du contenu"),
    P_body("Le présent mémoire ne prétend pas traiter l'ensemble des formes de plagiat existantes, ni couvrir toutes les technologies d'Intelligence Artificielle disponibles. Il se concentre sur la détection des similitudes textuelles et sémantiques entre travaux académiques, en s'appuyant sur les techniques d'embeddings vectoriels et de recherche vectorielle. La détection du plagiat par IA générative, c'est-à-dire l'identification de textes produits par des modèles de langage de type ChatGPT, est abordée comme perspective de recherche, mais ne constitue pas le cœur de l'expérimentation, compte tenu de la maturité encore partielle des solutions existantes dans ce domaine."),

    H2("I.6. Méthodes et techniques utilisées"),
    P_body("La démarche méthodologique adoptée combine plusieurs méthodes et techniques complémentaires, issues à la fois du génie logiciel classique et de la science des données moderne. Cette combinaison se justifie par la double nature du projet : d'une part, la conception d'une plateforme web opérationnelle, qui relève de l'ingénierie logicielle ; d'autre part, l'intégration et l'évaluation d'un modèle d'Intelligence Artificielle, qui relève de la démarche data science."),
    H3("I.6.1. Méthodes d'analyse et de conception"),
    P_body("Pour la modélisation du système d'information, la méthode Merise a été retenue. Elle permet de structurer la conception de la base de données relationnelle en distinguant les niveaux conceptuel, logique et physique, et reste largement enseignée et pratiquée dans les départements d'informatique des universités francophones. La modélisation UML (Unified Modeling Language) est utilisée en complément, pour la représentation des cas d'utilisation, des classes, des séquences et des activités. Ces deux méthodes classiques fournissent un cadre rigoureux pour la spécification de l'architecture logicielle et de la structure des données."),
    H3("I.6.2. Méthodologie data science : CRISP-DM"),
    P_body("Pour la composante Intelligence Artificielle du projet, la méthodologie CRISP-DM (Cross-Industry Standard Process for Data Mining) a été adoptée. Elle structure le projet en six phases : compréhension du domaine, compréhension des données, préparation des données, modélisation, évaluation et déploiement. Cette méthodologie, standard de référence en science des données, garantit une démarche rigoureuse et reproductible, depuis l'analyse du besoin jusqu'à l'évaluation quantitative des performances du modèle."),
    H3("I.6.3. Techniques de collecte de données"),
    P_body("Plusieurs techniques ont été mobilisées pour collecter les informations nécessaires au travail :"),
    P_bullet("La technique documentaire, qui a permis de consulter des ouvrages, des articles scientifiques, des thèses, des mémoires et des ressources en ligne en rapport avec le plagiat académique, l'Intelligence Artificielle, le traitement automatique du langage naturel et la détection automatique du plagiat."),
    P_bullet("La technique d'interview, conduite auprès du doyen de la Faculté des Sciences, des chefs de départements et de plusieurs enseignants, afin de comprendre les pratiques actuelles de dépôt et d'évaluation des travaux académiques, ainsi que les attentes vis-à-vis d'une plateforme anti-plagiat."),
    P_bullet("La technique d'observation, qui a consisté à observer directement les procédures de soumission, d'archivage et d'évaluation des travaux au sein de la faculté, ainsi qu'à examiner la structure et le contenu d'un échantillon de mémoires antérieurs."),
    P_bullet("La technique d'expérimentation, qui a consisté à constituer un corpus pilote de travaux académiques, à implémenter le pipeline de détection, et à évaluer les performances du système à l'aide de métriques quantitatives."),
    H3("I.6.4. Techniques d'évaluation"),
    P_body("L'évaluation des performances du système s'appuie sur les métriques classiques de l'apprentissage automatique : la précision (proportion des détections effectivement pertinentes), le rappel (proportion des cas réels de plagiat effectivement détectés), le F1-score (moyenne harmonique entre précision et rappel) et la courbe ROC (Receiver Operating Characteristic) avec calcul de l'aire sous la courbe (AUC). Ces métriques permettent de comparer objectivement l'approche sémantique proposée à une approche lexicale classique servant de baseline."),

    H2("I.7. Subdivision du travail"),
    P_body("Hormis l'introduction et la conclusion générales, le présent mémoire est subdivisé en quatre chapitres. Le premier chapitre présente les fondements de l'Intelligence Artificielle appliquée à la détection automatique du plagiat, en couvrant les concepts d'IA, de machine learning, de deep learning, de traitement automatique du langage naturel, d'embeddings vectoriels, de similarité sémantique et d'IA générative. Le deuxième chapitre propose un état de l'art du plagiat académique, en intégrant les nouvelles formes de plagiat liées à l'IA générative, et analyse les besoins spécifiques du cadre pilote. Le troisième chapitre est consacré à la conception de la plateforme web intelligente, avec une description de l'architecture modulaire, du pipeline IA et des choix de modélisation. Le quatrième chapitre présente l'implémentation, l'expérimentation et l'évaluation de la plateforme, ainsi que l'analyse des résultats obtenus."),
    new Paragraph({ children: [new PageBreak()] }),
  ];
}

// =========================================================================
// Re-export des autres chapitres depuis leurs modules respectifs
// =========================================================================
const { buildChapter1 } = require("./memoire_ch1.js");
const { buildChapter2 } = require("./memoire_ch2.js");
const { buildChapter3 } = require("./memoire_ch3.js");
const { buildChapter4 } = require("./memoire_ch4.js");
const { buildConclusion } = require("./memoire_conclusion.js");

// Bibliographie intégrée dans buildConclusion
function buildBibliographie() { return []; }

module.exports = {
  buildIntroduction,
  buildChapter1,
  buildChapter2,
  buildChapter3,
  buildChapter4,
  buildConclusion,
  buildBibliographie,
};
